"""Initial Database

Revision ID: 3d6dd8a48ed2
Revises: 
Create Date: 2021-01-18 21:36:28.126784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6dd8a48ed2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Locality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Day',
    sa.Column('locality_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temperature_max', sa.Integer(), nullable=True),
    sa.Column('temperature_min', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('text', sa.String(length=80), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('wind', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.String(length=30), nullable=True),
    sa.Column('icon_wind', sa.String(length=10), nullable=True),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.Column('sunset', sa.Time(), nullable=True),
    sa.Column('moonrise', sa.Time(), nullable=True),
    sa.Column('moonset', sa.Time(), nullable=True),
    sa.Column('moon_phases_icon', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['locality_id'], ['Locality.id'], ),
    sa.PrimaryKeyConstraint('locality_id', 'date')
    )
    op.create_table('Hour',
    sa.Column('locality_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour_data', sa.Time(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('text', sa.String(length=80), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('wind', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.String(length=30), nullable=True),
    sa.Column('icon_wind', sa.String(length=10), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locality_id'], ['Locality.id'], ),
    sa.PrimaryKeyConstraint('locality_id', 'date', 'hour_data')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Hour')
    op.drop_table('Day')
    op.drop_table('Locality')
    # ### end Alembic commands ###
